APP_NAME = "Local Friend"

WINDOW_MARGIN_X = 20
WINDOW_MARGIN_Y = 20

DEFAULT_STATUS_TEXT = "Idle"
DEFAULT_BUBBLE_TEXT = "Hi! I'm Local Friend 👀"
DEFAULT_AVATAR_TEXT = "🐱"

CAPTURE_INTERVAL_SECONDS = 20
COUNTDOWN_UPDATE_MS = 500
CAPTURE_HIDE_DELAY_MS = 300

MAX_IMAGE_WIDTH = 896

OLLAMA_MODEL = "qwen3.5:2b"
OLLAMA_TIMEOUT_SECONDS = 30.0
OLLAMA_KEEP_ALIVE = "5m"